apiVersion: rbac.authorization.k8s.io/v1	
kind: Role	
metadata:	
  name: 'cert-manager:leaderelection'	
  namespace: kube-system	
rules:	
  - apiGroups:	
      - coordination.k8s.io	
    resourceNames:	
      - cert-manager-controller	
    resources:	
      - leases	
    verbs:	
      - get	
      - update	
      - patch	
  - apiGroups:	
      - coordination.k8s.io	
    resources:	
      - leases	
    verbs:	
      - create
